#!/bin/bash
yum install httpd git tomcat -y
sudo yum install tomcat-webapps tomcat-admin-webapps
sudo systemctl start tomcat
sudo systemctl enable tomcat
#git clone https://github.com/Shivbir/Sample-WebApplication.git
#cp -r ./Sample-WebApplication/service.jar /usr/share/tomcat/webapps/
#cp -r ./Sample-WebApplication/demo-0.0.1-SNAPSHOT.jar /usr/share/tomcat/webapps/
#sudo systemctl restart tomcat


